# Generated by Django 4.0.3 on 2022-05-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='uploads/users'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(blank=True, upload_to='uploads/users'),
        ),
        migrations.AlterField(
            model_name='review',
            name='img',
            field=models.ImageField(blank=True, upload_to='uploads/reviews'),
        ),
    ]
