# Generated by Django 4.0.3 on 2022-04-27 08:16

import datetime
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=5000)),
                ('img', models.ImageField(blank=True, upload_to='uploads/movies')),
                ('thumbnail', models.ImageField(blank=True, upload_to='uploads/movies')),
                ('director', models.CharField(max_length=150)),
                ('actor', models.CharField(max_length=150)),
                ('year', models.DateField(default=datetime.date(2000, 1, 1))),
                ('category', models.CharField(max_length=150)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
