# Generated by Django 4.0.3 on 2022-04-26 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('O', 'Prefer Not to Say'), ('M', 'Male'), ('F', 'Female')], default='O', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='securityAnswer',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='securityQuestion',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
