# Generated by Django 4.0.3 on 2022-05-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_thumbnail_alter_customuser_profile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='groupAdminApply',
            new_name='groupAdminRequest',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='isMainAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
