# Generated by Django 4.0.3 on 2022-05-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_review_book_review_movie_alter_review_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='img',
            field=models.ImageField(blank=True, upload_to='uploads/groups'),
        ),
        migrations.AddField(
            model_name='movie',
            name='area',
            field=models.IntegerField(choices=[(0, '中国'), (1, '美国'), (2, '英国'), (3, '韩国'), (4, '日本'), (5, '泰国'), (6, '马来西亚')], default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.IntegerField(choices=[(0, '其他'), (1, '爱情'), (2, '恐怖'), (3, '悬疑'), (4, '冒险'), (5, '喜剧'), (6, '动作'), (7, '科幻'), (8, '综艺'), (9, '动漫'), (10, '卡通'), (11, 'LGBT')], default=0),
        ),
    ]
