# Generated by Django 4.0.3 on 2022-05-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_feedback_category_alter_review_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='rateScore',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
