# Generated by Django 4.0.3 on 2022-06-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_group_thumbnail_alter_userbook_ratescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='firstName',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastName',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='groupadminrequest',
            unique_together={('group', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='groupfeed',
            unique_together={('group', 'feed')},
        ),
        migrations.AlterUniqueTogether(
            name='userfeed',
            unique_together={('feed', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='userreview',
            unique_together={('review', 'user')},
        ),
    ]
