# Generated by Django 4.0.3 on 2022-05-03 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_feedback_category_alter_report_reportfeed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reportFeed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.feed'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reportReview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.review'),
        ),
    ]
