# Generated by Django 4.0.3 on 2022-05-08 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_report_reportfeed_alter_report_reportreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.IntegerField(choices=[(0, '其他'), (1, '爱情'), (2, '恐怖'), (3, '悬疑'), (4, '科幻'), (5, '艺术'), (6, '体育'), (7, '烹饪'), (8, '漫画'), (9, '教育'), (10, '哲学'), (11, '文学')], default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='securityQuestion',
            field=models.IntegerField(choices=[(1, '您最喜欢的颜色是'), (2, '您最讨厌的食物'), (3, '您的最要好闺蜜/兄弟是'), (4, '您的爱好是'), (5, '您的初恋是')], default=0),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.IntegerField(choices=[(1, 'BUG反馈'), (2, '网站反馈'), (3, '其它')], default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.IntegerField(choices=[(0, '其他'), (1, '爱情'), (2, '恐怖'), (3, '悬疑'), (4, '冒险'), (5, '喜剧'), (6, '动作'), (7, '科幻'), (8, '综艺'), (9, '动漫'), (10, '卡通')], default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.IntegerField(choices=[(1, '垃圾内容'), (2, '色情内容'), (3, '非法活动'), (4, '侵犯版权'), (5, '骚扰、欺凌和威胁'), (6, '仇恨言论'), (7, '暴力内容')], default=0),
        ),
        migrations.CreateModel(
            name='userReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('O', 'Other'), ('L', 'Like'), ('D', 'Dislike')], default='O', max_length=10)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('O', 'Other'), ('L', 'Like'), ('D', 'Dislike')], default='O', max_length=10)),
                ('isSaved', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAdmin', models.BooleanField(default=False)),
                ('isBanned', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('O', 'Other'), ('L', 'Like'), ('D', 'Dislike')], default='O', max_length=10)),
                ('isFollowed', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('O', 'Other'), ('L', 'Like'), ('D', 'Dislike')], default='O', max_length=10)),
                ('isSaved', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='groupFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPin', models.BooleanField(default=False)),
                ('isFeatured', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.feed')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
            ],
        ),
    ]
