# Generated by Django 4.0.3 on 2022-05-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_book_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='banDue',
            field=models.DateTimeField(),
        ),
    ]
