# Generated by Django 4.0.3 on 2022-06-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='isTag',
            field=models.BooleanField(default=True),
        ),
    ]
