# Generated by Django 4.0.3 on 2022-05-08 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_book_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.review'),
        ),
    ]
