# Generated by Django 4.0.3 on 2022-05-09 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_book_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='banDue',
        ),
        migrations.AddField(
            model_name='userbook',
            name='isRated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbook',
            name='rateScore',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='usermovie',
            name='isRated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermovie',
            name='rateScore',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='response',
            field=models.CharField(choices=[('O', 'Other'), ('L', 'Like'), ('D', 'Dislike')], default='O', max_length=10),
        ),
        migrations.AlterField(
            model_name='userfeed',
            name='response',
            field=models.CharField(choices=[('O', 'Other'), ('L', 'Like'), ('D', 'Dislike')], default='O', max_length=10),
        ),
        migrations.AlterField(
            model_name='usermovie',
            name='response',
            field=models.CharField(choices=[('O', 'Other'), ('L', 'Like'), ('D', 'Dislike')], default='O', max_length=10),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='response',
            field=models.CharField(choices=[('O', 'Other'), ('L', 'Like'), ('D', 'Dislike')], default='O', max_length=10),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.review'),
        ),
    ]
