# Generated by Django 4.0.3 on 2022-05-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_usergroup_bandue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='banDue',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
