# Generated by Django 4.0.3 on 2022-05-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_userreview_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='rateScore',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='usermovie',
            name='rateScore',
            field=models.IntegerField(default=-1),
        ),
    ]
