# Generated by Django 4.0.3 on 2022-05-10 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_usergroup_bandue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupfeed',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.feed', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='usergroup',
            unique_together={('group', 'user')},
        ),
    ]
