# Generated by Django 4.0.3 on 2022-05-10 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_groupfeed_feed_alter_usergroup_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupfeed',
            name='feed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.feed'),
        ),
    ]
