# Generated by Django 4.0.3 on 2022-06-03 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_tag_tagfeed_feed_belongtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertag',
            name='isJoined',
        ),
        migrations.AlterField(
            model_name='usertag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tag'),
        ),
    ]
