# Generated by Django 4.0.3 on 2022-06-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_usertag_isjoined_alter_usertag_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='isTag',
        ),
    ]
