# Generated by Django 4.0.3 on 2022-05-11 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_groupadminapply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupfeed',
            name='isNormal',
        ),
    ]
