# Generated by Django 4.0.3 on 2022-06-04 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_feed_istag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeed',
            name='isFollowed',
        ),
    ]
